### ISSUE TITLE
build fails on windows 7 64 bit

### ISSUE THREAD

**Issue by aveshd** [hughperkins/jeigen#2] opened 2014-05-10 04:33 UTC
Hi,
I was following your intstruction and the build failed. it complained there was an error on line#49 of build.xml can not find c:\us\bin\cmake. 

So I changed the line #3 of buiold.xml to <property name="cmake_home" value="C:\Program Files (x86)\CMake 2.8" />

and it worked. build is successful.

**Comment by hughperkins** [comment] 2015-01-17 11:41
I updated the build a lot a few weeks ago, and hopefully this fixes the issue?  Closing for now.  Please feel free to re-open if the issue is still present.

**Closed by hughperkins** 2015-01-17 11:41 UTC
